# Generated by Django 5.2.2 on 2025-10-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_posts', models.IntegerField()),
                ('completed_posts', models.IntegerField(default=0)),
                ('failed_posts', models.IntegerField(default=0)),
                ('current_post_id', models.IntegerField(blank=True, null=True)),
                ('current_post_title', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketplacePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='posts/')),
                ('scheduled_time', models.DateTimeField()),
                ('posted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.facebookaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('session_expired', 'Session Expired'), ('network_error', 'Network Error'), ('captcha', 'CAPTCHA Required'), ('rate_limit', 'Rate Limited'), ('validation_error', 'Validation Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=50)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='error_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='postings.marketplacepost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['posted'], name='posted_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['scheduled_time'], name='scheduled_time_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['account', 'posted'], name='account_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['posted', 'scheduled_time'], name='posted_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
    ]
