# Generated by Django 5.2.2 on 2025-06-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='location',
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='meetup_preference',
            field=models.CharField(choices=[('door_pickup', 'Door Pickup'), ('public_meetup', 'Public Meetup'), ('door_dropoff', 'Door Dropoff')], default='public_meetup', max_length=20),
        ),
    ]
