# Generated by Django 5.2.2 on 2025-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepost',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='posts/additional/'),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='category',
            field=models.CharField(choices=[('vehicles', 'Vehicles'), ('property_rentals', 'Property Rentals'), ('apparel', 'Apparel'), ('classic_cars', 'Classic Cars'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('home_goods', 'Home Goods'), ('jewelry', 'Jewelry'), ('musical_instruments', 'Musical Instruments'), ('sporting_goods', 'Sporting Goods'), ('toys_games', 'Toys & Games'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='shipping_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
    ]
