# Generated by Django 5.2.2 on 2025-06-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_marketplacepost_additional_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketplacepost',
            old_name='is_negotiable',
            new_name='door_dropoff',
        ),
        migrations.RenameField(
            model_name='marketplacepost',
            old_name='shipping_available',
            new_name='door_pickup',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='availability',
            field=models.CharField(choices=[('single_item', 'List as Single Item'), ('in_stock', 'List as Stock')], default='single_item', max_length=20),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='public_meetup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - Optional identifier for your product', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='category',
            field=models.CharField(choices=[('home_garden_tools', 'Home & Garden - Tools'), ('home_garden_furniture', 'Home & Garden - Furniture'), ('home_garden_household', 'Home & Garden - Household'), ('home_garden_garden', 'Home & Garden - Garden'), ('home_garden_appliance', 'Home & Garden - Appliance'), ('entertainment_video_games', 'Entertainment - Video Games'), ('entertainment_books', 'Entertainment - Books'), ('entertainment_movies_music', 'Entertainment - Movies & Music'), ('clothing_bags_luggage', 'Clothing and Accessories - Bags & Luggage'), ('clothing_womens', "Clothing and Accessories - Women's Clothing & Shoes"), ('clothing_mens', "Clothing and Accessories - Men's Clothing & Shoes"), ('clothing_jewelry', 'Clothing and Accessories - Jewelry & Accessories'), ('family_toys_games', 'Family - Toys & Games'), ('family_baby_kids', 'Family - Baby & Kids'), ('family_pet_supplies', 'Family - Pet Supplies'), ('family_health_beauty', 'Family - Health & Beauty'), ('electronics_mobile', 'Electronics - Mobile Phones'), ('electronics_computers', 'Electronics - Electronics & Computers'), ('hobbies_sports', 'Hobbies - Sports and Outdoors'), ('hobbies_musical', 'Hobbies - Musical Instruments'), ('hobbies_arts', 'Hobbies - Arts & Crafts'), ('hobbies_antiques', 'Hobbies - Antiques & Collectables'), ('hobbies_auto_parts', 'Hobbies - Auto Parts'), ('hobbies_bicycles', 'Hobbies - Bicycles'), ('classified_garage_sales', 'Classified - Garage Sales'), ('classified_miscellaneous', 'Classified - Miscellaneous')], default='classified_miscellaneous', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_like_new', 'Used - Like New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for better searchability', max_length=255),
        ),
    ]
