# Generated by Django 5.2.2 on 2025-06-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_remove_marketplacepost_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='meetup_preference',
        ),
    ]
