# Generated by Django 5.2.2 on 2025-10-17 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_remove_marketplacepost_meetup_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacepost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
