# Generated by Django 5.2.2 on 2025-06-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_rename_is_negotiable_marketplacepost_door_dropoff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='door_dropoff',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='door_pickup',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='public_meetup',
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='meetup_preference',
            field=models.CharField(choices=[('public_meetup', 'Public Meetup'), ('door_pickup', 'Door Pickup'), ('door_dropoff', 'Door Drop Off')], default='public_meetup', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='availability',
            field=models.CharField(choices=[('single_item', 'List as Single Item'), ('in_stock', 'List as In Stock')], default='single_item', max_length=20),
        ),
    ]
