# Generated by Django 5.2.2 on 2025-06-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_remove_marketplacepost_door_dropoff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='location',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='marketplacepost',
            name='size',
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='availability',
            field=models.CharField(choices=[('single_item', 'List as Single Item'), ('in_stock', 'List as In Stock')], default='in_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='category',
            field=models.CharField(choices=[('home_garden_tools', 'Home & Garden - Tools'), ('home_garden_furniture', 'Home & Garden - Furniture'), ('home_garden_household', 'Home & Garden - Household'), ('home_garden_garden', 'Home & Garden - Garden'), ('home_garden_appliance', 'Home & Garden - Appliance'), ('entertainment_video_games', 'Entertainment - Video Games'), ('entertainment_books', 'Entertainment - Books'), ('entertainment_movies_music', 'Entertainment - Movies & Music'), ('clothing_bags_luggage', 'Clothing and Accessories - Bags & Luggage'), ('clothing_womens', "Clothing and Accessories - Women's Clothing & Shoes"), ('clothing_mens', "Clothing and Accessories - Men's Clothing & Shoes"), ('clothing_jewelry', 'Clothing and Accessories - Jewelry & Accessories'), ('family_toys_games', 'Family - Toys & Games'), ('family_baby_kids', 'Family - Baby & Kids'), ('family_pet_supplies', 'Family - Pet Supplies'), ('family_health_beauty', 'Family - Health & Beauty'), ('electronics_mobile', 'Electronics - Mobile Phones'), ('electronics_computers', 'Electronics - Electronics & Computers'), ('hobbies_sports', 'Hobbies - Sports and Outdoors'), ('hobbies_musical', 'Hobbies - Musical Instruments'), ('hobbies_arts', 'Hobbies - Arts & Crafts'), ('hobbies_antiques', 'Hobbies - Antiques & Collectables'), ('hobbies_auto_parts', 'Hobbies - Auto Parts'), ('hobbies_bicycles', 'Hobbies - Bicycles'), ('classified_garage_sales', 'Classified - Garage Sales'), ('classified_miscellaneous', 'Classified - Miscellaneous')], default='home_garden_furniture', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='meetup_preference',
            field=models.CharField(choices=[('public_meetup', 'Public Meetup'), ('door_pickup', 'Door Pickup'), ('door_dropoff', 'Door Drop Off'), ('both_door', 'Both Door Pickup & Drop Off')], default='door_dropoff', max_length=20),
        ),
    ]
