# Generated by Django 5.2.2 on 2025-10-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_marketplacepost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
