# Generated by Django 5.2.2 on 2025-10-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('postings', '0005_alter_marketplacepost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacepost',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['posted'], name='posted_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['scheduled_time'], name='scheduled_time_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['account', 'posted'], name='account_posted_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['posted', 'scheduled_time'], name='posted_scheduled_idx'),
        ),
    ]
