# Generated by Django 5.2.2 on 2025-06-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_remove_marketplacepost_additional_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='meetup_preference',
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='meetup_preferences',
            field=models.JSONField(default=list, help_text='List of selected meetup preferences'),
        ),
    ]
