# Generated by Django 5.2.2 on 2025-10-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('postings', '0006_alter_marketplacepost_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('session_expired', 'Session Expired'), ('network_error', 'Network Error'), ('captcha', 'CAPTCHA Required'), ('rate_limit', 'Rate Limited'), ('validation_error', 'Validation Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=50)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='error_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_posts', models.IntegerField()),
                ('completed_posts', models.IntegerField(default=0)),
                ('failed_posts', models.IntegerField(default=0)),
                ('current_post_id', models.IntegerField(blank=True, null=True)),
                ('current_post_title', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='marketplacepost',
            index=models.Index(fields=['status'], name='status_idx'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='postings.marketplacepost'),
        ),
    ]
