# Generated by Django 5.2.2 on 2025-06-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_remove_marketplacepost_meetup_preference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplacepost',
            name='meetup_preferences',
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='door_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='door_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marketplacepost',
            name='public_meetup',
            field=models.BooleanField(default=False),
        ),
    ]
