# Generated by Django 5.2.2 on 2025-06-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0007_remove_marketplacepost_meetup_preferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacepost',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit - Optional identifier for your product', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacepost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for better searchability', max_length=255, null=True),
        ),
    ]
